sudo: required
language: python

# which python versions to test
python:
  - "3.4"
  - "3.5"
  - "3.6"

# Cache directory $HOME/.cache/pip
cache: pip

# command before installation: install all dependencies and run CMAKE config
before_install:
  - sudo apt-get install gfortran
  - sudo apt-get install openmpi-bin libopenmpi-dev
  - ompi_info
  - python -m pip install --upgrade pip
  - python -m pip install -r requirements.txt
  - python -m pip uninstall -y spl

# command to install project
install:
  - python -m pip install .

before_script:
  - mkdir pytest
  - cp mpi_tester.py pytest

# command to run tests
script:
  - cd pytest
  - python -m pytest --pyargs spl -m "not parallel"
  - python mpi_tester.py --pyargs spl -m "parallel"
  - cd -

after_script:
  - rm -rf pytest
