sudo: required
language: python

# which python versions to test
python:
#  - "2.6"
#  - "2.7"
#  - "3.2"
#  - "3.3"
  - "3.4"
#  - "3.5"
#  - "3.5-dev" # 3.5 development branch
#  - "3.6"
#  - "3.6-dev" # 3.6 development branch
#  - "3.7-dev" # 3.7 development branch
#  - "nightly"

virtualenv:
    system_site_packages: true

# command before installation
before_install:
  - sudo apt-get install gfortran
  - sudo apt-get install openmpi-bin libopenmpi-dev
  - ompi_info
  - mkdir -p usr
  - export FORTRAN_INSTALL_DIR=$TRAVIS_BUILD_DIR/usr
  - mkdir build && cd build
  - cmake -DCMAKE_Fortran_FLAGS="-fPIC" -DBUILD_TESTING=ON -DCMAKE_INSTALL_PREFIX=$FORTRAN_INSTALL_DIR  ..
  - make && make install
  - cd ..
# command to install dependencies
  - pip3 install -r requirements.txt

# command to install project
install:
  - pip3 install . 

# command to run tests
script:
#  - pytest # or py.test for Python versions 3.5 and below
#  - pytest tests/caid
  - cd build ; make test ; cd ..
  - pytest --full-trace tests/ddm
  - pytest tests/linalg
  - pytest tests/test_core.py
  - pytest tests/test_integration.py
  - pytest tests/test_projector.py
